services:
  mysql:
    image: 'mysql/mysql-server:latest'
    environment:
      - 'MYSQL_DATABASE=pdmdb'
      - 'MYSQL_PASSWORD=123456Aa@$'
      - 'MYSQL_ROOT_PASSWORD=123456Aa@$'
      - 'MYSQL_USER=root'
    ports:
      - '3307:3306/tcp'
    restart: unless-stopped
  # sqlserver:
  #   image: 'mcr.microsoft.com/mssql/server:latest'
  #   environment:
  #     - 'ACCEPT_EULA=yes'
  #     - 'MSSQL_PID=express'
  #     - 'MSSQL_SA_PASSWORD=verYs3cret'
  #   ports:
  #     - '1433'
# docker pull mysql/mysql-server:latest
# docker run -e "ACCEPT_EULA=1" -e "MSSQL_SA_PASSWORD=123456Aa@$" -e "MSSQL_PID=Developer" -e "MSSQL_USER=root" -p 1433:1433 -d --name=pdmdb mysql/mysql-server:latest
# docker-compose up -d
# docker-compose down -d
#port 3306